[package]
name = "commitlib"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
pod2 = { workspace = true }
serde = { workspace = true }

common = { path = "../common" }
pod2utils = { path = "../pod2utils" }
